# Generated by Django 3.1.7 on 2021-02-28 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.UUIDField(verbose_name="код")),
                ("name", models.CharField(max_length=250, verbose_name="наименование")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orgunits.organization",
                        verbose_name="вышестоящая организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "организации",
                "verbose_name_plural": "организация",
                "ordering": ["name"],
            },
        ),
    ]
